---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-homeassistant-registry-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 45Gi
